In [1]:
import pandas as pd

In [2]:
data = {
    "Yil" : [2021,2020,2019,2018,2017,2016,2015,2010],
    "Aholi soni" : [33.9,33.5,32.9,32.5,31.9,31.4,30.9,28.5],
    "Temp" : [1.54,1.44,1.39,1.32,1.29,1.26,1.24,0.24],
}

In [3]:
data

{'Yil': [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
 'Aholi soni': [33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
 'Temp': [1.54, 1.44, 1.39, 1.32, 1.29, 1.26, 1.24, 0.24]}

In [4]:
df = pd.DataFrame(data)

In [5]:
df

    Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.44
2  2019        32.9  1.39
3  2018        32.5  1.32
4  2017        31.9  1.29
5  2016        31.4  1.26
6  2015        30.9  1.24
7  2010        28.5  0.24

In [6]:
df.shape

(8, 3)

In [7]:
df.head()

    Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.44
2  2019        32.9  1.39
3  2018        32.5  1.32
4  2017        31.9  1.29

In [8]:
df.head(3)

    Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.44
2  2019        32.9  1.39

In [9]:
df = pd.DataFrame(data, columns=["Yil","Temp","Aholi soni", "yangi"])

In [10]:
df

    Yil  Temp  Aholi soni yangi
0  2021  1.54        33.9   NaN
1  2020  1.44        33.5   NaN
2  2019  1.39        32.9   NaN
3  2018  1.32        32.5   NaN
4  2017  1.29        31.9   NaN
5  2016  1.26        31.4   NaN
6  2015  1.24        30.9   NaN
7  2010  0.24        28.5   NaN

In [11]:
df = pd.DataFrame(data, columns=["Yil","Temp","Aholi soni", "yangi"], index=[5,10,15,20,25,30,35,40])

In [12]:
df

     Yil  Temp  Aholi soni yangi
5   2021  1.54        33.9   NaN
10  2020  1.44        33.5   NaN
15  2019  1.39        32.9   NaN
20  2018  1.32        32.5   NaN
25  2017  1.29        31.9   NaN
30  2016  1.26        31.4   NaN
35  2015  1.24        30.9   NaN
40  2010  0.24        28.5   NaN

In [13]:
aholi = df["Aholi soni"]

In [14]:
aholi

5     33.9
10    33.5
15    32.9
20    32.5
25    31.9
30    31.4
35    30.9
40    28.5
Name: Aholi soni, dtype: float64

In [15]:
df.yangi = 0

In [16]:
df

     Yil  Temp  Aholi soni  yangi
5   2021  1.54        33.9      0
10  2020  1.44        33.5      0
15  2019  1.39        32.9      0
20  2018  1.32        32.5      0
25  2017  1.29        31.9      0
30  2016  1.26        31.4      0
35  2015  1.24        30.9      0
40  2010  0.24        28.5      0

In [21]:
df.shape

(8, 4)

In [19]:
df.yangi = pd.Series([1500, 1600, 1240, 874], index=[5,10,15,20])

In [20]:
df

     Yil  Temp  Aholi soni   yangi
5   2021  1.54        33.9  1500.0
10  2020  1.44        33.5  1600.0
15  2019  1.39        32.9  1240.0
20  2018  1.32        32.5   874.0
25  2017  1.29        31.9     NaN
30  2016  1.26        31.4     NaN
35  2015  1.24        30.9     NaN
40  2010  0.24        28.5     NaN

In [29]:
val = [1500, 1600, 1240, 874, 500, 600, 798,120]

In [30]:
df.yangi = val

In [31]:
df

     Yil  Temp  Aholi soni  yangi
5   2021  1.54        33.9   1500
10  2020  1.44        33.5   1600
15  2019  1.39        32.9   1240
20  2018  1.32        32.5    874
25  2017  1.29        31.9    500
30  2016  1.26        31.4    600
35  2015  1.24        30.9    798
40  2010  0.24        28.5    120

In [32]:
df['700+'] = df.yangi>700

In [33]:
df

     Yil  Temp  Aholi soni  yangi   700+
5   2021  1.54        33.9   1500   True
10  2020  1.44        33.5   1600   True
15  2019  1.39        32.9   1240   True
20  2018  1.32        32.5    874   True
25  2017  1.29        31.9    500  False
30  2016  1.26        31.4    600  False
35  2015  1.24        30.9    798   True
40  2010  0.24        28.5    120  False

In [34]:
del df['700+']

In [35]:
df

     Yil  Temp  Aholi soni  yangi
5   2021  1.54        33.9   1500
10  2020  1.44        33.5   1600
15  2019  1.39        32.9   1240
20  2018  1.32        32.5    874
25  2017  1.29        31.9    500
30  2016  1.26        31.4    600
35  2015  1.24        30.9    798
40  2010  0.24        28.5    120