In [1]:
import pandas as pd

In [2]:
data = {
    "Yil" : [2021,2020,2019,2018,2017,2016,2015,2010],
    "Aholi soni" : [33.9,33.5,32.9,32.5,31.9,31.4,30.9,28.5],
    "Temp" : [1.54,1.44,1.39,1.32,1.29,1.26,1.24,0.24],
}

In [3]:
data

{'Yil': [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
 'Aholi soni': [33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
 'Temp': [1.54, 1.44, 1.39, 1.32, 1.29, 1.26, 1.24, 0.24]}

In [4]:
df = pd.DataFrame(data)

In [5]:
df

    Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.44
2  2019        32.9  1.39
3  2018        32.5  1.32
4  2017        31.9  1.29
5  2016        31.4  1.26
6  2015        30.9  1.24
7  2010        28.5  0.24

In [6]:
df.shape

(8, 3)

In [7]:
df.head()

    Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.44
2  2019        32.9  1.39
3  2018        32.5  1.32
4  2017        31.9  1.29

In [8]:
df.head(3)

    Yil  Aholi soni  Temp
0  2021        33.9  1.54
1  2020        33.5  1.44
2  2019        32.9  1.39