In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Yil' : [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
    'Aholi soni' : [33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
    'Temp' : [1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53],
    'Zichlik' : [79.77, 78.68, 77.53, 76.34, 75.13, 73.91, 72.71, 67.03]
}
df = pd.DataFrame(data)
df

    Yil  Aholi soni  Temp  Zichlik
0  2021        33.9  1.54    79.77
1  2020        33.5  1.48    78.68
2  2019        32.9  1.56    77.53
3  2018        32.5  1.62    76.34
4  2017        31.9  1.65    75.13
5  2016        31.4  1.66    73.91
6  2015        30.9  1.64    72.71
7  2010        28.5  1.53    67.03

In [11]:
data = df['Aholi soni']
data

0    33.9
1    33.5
2    32.9
3    32.5
4    31.9
5    31.4
6    30.9
7    28.5
Name: Aholi soni, dtype: float64

In [4]:
type(data)

pandas.core.series.Series

In [5]:
data = df[['Aholi soni']]
data

   Aholi soni
0        33.9
1        33.5
2        32.9
3        32.5
4        31.9
5        31.4
6        30.9
7        28.5

In [6]:
type(data)

pandas.core.frame.DataFrame

In [12]:
data[0:4]

0    33.9
1    33.5
2    32.9
3    32.5
Name: Aholi soni, dtype: float64

In [14]:
data[[2,4,6,0]]

2    32.9
4    31.9
6    30.9
0    33.9
Name: Aholi soni, dtype: float64

In [15]:
obj = pd.Series(np.arange(8.), index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
f    5.0
g    6.0
h    7.0
dtype: float64

In [16]:
obj['a']

np.float64(0.0)

In [17]:
obj[0:4]

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [19]:
#Bu_usul_faqat_harflilar_uchun_ishlaydi
obj['a':'f']

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
f    5.0
dtype: float64

In [20]:
#Qiymat_ozgartirish
obj['a':'c'] = 10

In [21]:
obj

a    10.0
b    10.0
c    10.0
d     3.0
e     4.0
f     5.0
g     6.0
h     7.0
dtype: float64

In [22]:
obj[obj==10]

a    10.0
b    10.0
c    10.0
dtype: float64

In [23]:
obj[obj<10]

d    3.0
e    4.0
f    5.0
g    6.0
h    7.0
dtype: float64

In [24]:
obj[obj>10]

Series([], dtype: float64)

In [25]:
type(obj[obj>10])

pandas.core.series.Series