In [1]:
import numpy as np
import pandas as pd

In [2]:
uz = {2020:33.5, 2019:32.9, 2018:32.5, 2017:31.8, 2016:30.5, 2015:29.7}
kz = {2020:18.8, 2019:18.1, 2018:17.8, 2017:17.5, 2016:17.3, 2015:17.1}
tj = {2020:9.5, 2019:9.3, 2018:8.9, 2017:8.6, 2016:8.3, 2015:7.4}
kg = {2020:6.5, 2019:6.4, 2018:6.3, 2017:6.1, 2016:5.9, 2015:5.5}
tr = {2020:6.0, 2019:5.8, 2018:5.7, 2017:5.5, 2016:5.3, 2015:5.0}

df = pd.DataFrame({'Uzbekistan':uz, 'Kazakhstan':kz, 'Tajikistan':tj, 'Kyrgyzstan':kg, 'Turkey':tr})
df

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkey
2020        33.5        18.8         9.5         6.5     6.0
2019        32.9        18.1         9.3         6.4     5.8
2018        32.5        17.8         8.9         6.3     5.7
2017        31.8        17.5         8.6         6.1     5.5
2016        30.5        17.3         8.3         5.9     5.3
2015        29.7        17.1         7.4         5.5     5.0

In [4]:
type(df['Uzbekistan'])

pandas.core.series.Series

In [5]:
type(df[['Uzbekistan']])

pandas.core.frame.DataFrame

In [7]:
df['Uzbekistan'].to_numpy()

array([33.5, 32.9, 32.5, 31.8, 30.5, 29.7])

In [8]:
df[['Uzbekistan']].to_numpy()

array([[33.5],
       [32.9],
       [32.5],
       [31.8],
       [30.5],
       [29.7]])

In [9]:
df[3:]

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkey
2017        31.8        17.5         8.6         6.1     5.5
2016        30.5        17.3         8.3         5.9     5.3
2015        29.7        17.1         7.4         5.5     5.0

In [10]:
df

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkey
2020        33.5        18.8         9.5         6.5     6.0
2019        32.9        18.1         9.3         6.4     5.8
2018        32.5        17.8         8.9         6.3     5.7
2017        31.8        17.5         8.6         6.1     5.5
2016        30.5        17.3         8.3         5.9     5.3
2015        29.7        17.1         7.4         5.5     5.0

In [11]:
df>5

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkey
2020        True        True        True        True    True
2019        True        True        True        True    True
2018        True        True        True        True    True
2017        True        True        True        True    True
2016        True        True        True        True    True
2015        True        True        True        True   False

In [12]:
df>10

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkey
2020        True        True       False       False   False
2019        True        True       False       False   False
2018        True        True       False       False   False
2017        True        True       False       False   False
2016        True        True       False       False   False
2015        True        True       False       False   False

In [13]:
df<10

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkey
2020       False       False        True        True    True
2019       False       False        True        True    True
2018       False       False        True        True    True
2017       False       False        True        True    True
2016       False       False        True        True    True
2015       False       False        True        True    True

In [14]:
df

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkey
2020        33.5        18.8         9.5         6.5     6.0
2019        32.9        18.1         9.3         6.4     5.8
2018        32.5        17.8         8.9         6.3     5.7
2017        31.8        17.5         8.6         6.1     5.5
2016        30.5        17.3         8.3         5.9     5.3
2015        29.7        17.1         7.4         5.5     5.0

In [15]:
df[['Uzbekistan']][df['Uzbekistan']>32]

      Uzbekistan
2020        33.5
2019        32.9
2018        32.5

In [16]:
dfuz = df['Uzbekistan']

In [20]:
dfuz

2020    33.5
2019    32.9
2018    32.5
2017    31.8
2016    30.5
2015    29.7
Name: Uzbekistan, dtype: float64

In [22]:
dfuz[dfuz>32]

2020    33.5
2019    32.9
2018    32.5
Name: Uzbekistan, dtype: float64

In [23]:
dfuz>32

2020     True
2019     True
2018     True
2017    False
2016    False
2015    False
Name: Uzbekistan, dtype: bool

In [24]:
df2 = df.transpose(copy=True)

In [25]:
df2

            2020  2019  2018  2017  2016  2015
Uzbekistan  33.5  32.9  32.5  31.8  30.5  29.7
Kazakhstan  18.8  18.1  17.8  17.5  17.3  17.1
Tajikistan   9.5   9.3   8.9   8.6   8.3   7.4
Kyrgyzstan   6.5   6.4   6.3   6.1   5.9   5.5
Turkey       6.0   5.8   5.7   5.5   5.3   5.0

In [26]:
df

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkey
2020        33.5        18.8         9.5         6.5     6.0
2019        32.9        18.1         9.3         6.4     5.8
2018        32.5        17.8         8.9         6.3     5.7
2017        31.8        17.5         8.6         6.1     5.5
2016        30.5        17.3         8.3         5.9     5.3
2015        29.7        17.1         7.4         5.5     5.0

In [27]:
df2[df2>6]

            2020  2019  2018  2017  2016  2015
Uzbekistan  33.5  32.9  32.5  31.8  30.5  29.7
Kazakhstan  18.8  18.1  17.8  17.5  17.3  17.1
Tajikistan   9.5   9.3   8.9   8.6   8.3   7.4
Kyrgyzstan   6.5   6.4   6.3   6.1   NaN   NaN
Turkey       NaN   NaN   NaN   NaN   NaN   NaN

In [28]:
df2[df2[2015]>6]

            2020  2019  2018  2017  2016  2015
Uzbekistan  33.5  32.9  32.5  31.8  30.5  29.7
Kazakhstan  18.8  18.1  17.8  17.5  17.3  17.1
Tajikistan   9.5   9.3   8.9   8.6   8.3   7.4