In [1]:
import numpy as np
import pandas as pd

In [2]:
uz = {2020:33.5, 2019:32.9, 2018:32.5, 2017:31.8, 2016:30.5, 2015:29.7}
kz = {2020:18.8, 2019:18.1, 2018:17.8, 2017:17.5, 2016:17.3, 2015:17.1}
tj = {2020:9.5, 2019:9.3, 2018:8.9, 2017:8.6, 2016:8.3, 2015:7.4}
kg = {2020:6.5, 2019:6.4, 2018:6.3, 2017:6.1, 2016:5.9, 2015:5.5}
tr = {2020:6.0, 2019:5.8, 2018:5.7, 2017:5.5, 2016:5.3, 2015:5.0}

df = pd.DataFrame({'Uzbekistan':uz, 'Kazakhstan':kz, 'Tajikistan':tj, 'Kyrgyzstan':kg, 'Turkey':tr})
df

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkey
2020        33.5        18.8         9.5         6.5     6.0
2019        32.9        18.1         9.3         6.4     5.8
2018        32.5        17.8         8.9         6.3     5.7
2017        31.8        17.5         8.6         6.1     5.5
2016        30.5        17.3         8.3         5.9     5.3
2015        29.7        17.1         7.4         5.5     5.0

In [3]:
df.loc[2020]

Uzbekistan    33.5
Kazakhstan    18.8
Tajikistan     9.5
Kyrgyzstan     6.5
Turkey         6.0
Name: 2020, dtype: float64

In [4]:
df.loc[[2020, 2018]]

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkey
2020        33.5        18.8         9.5         6.5     6.0
2018        32.5        17.8         8.9         6.3     5.7

In [5]:
df.loc[[2020, 2018],['Uzbekistan', 'Kazakhstan']]

      Uzbekistan  Kazakhstan
2020        33.5        18.8
2018        32.5        17.8

In [8]:
#index orqali murojaat qilish
df.iloc[[0,2], [0,1]]

      Uzbekistan  Kazakhstan
2020        33.5        18.8
2018        32.5        17.8

In [9]:
df

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkey
2020        33.5        18.8         9.5         6.5     6.0
2019        32.9        18.1         9.3         6.4     5.8
2018        32.5        17.8         8.9         6.3     5.7
2017        31.8        17.5         8.6         6.1     5.5
2016        30.5        17.3         8.3         5.9     5.3
2015        29.7        17.1         7.4         5.5     5.0

In [10]:
#Joyiga ishora qilish at
df.at[2017,'Uzbekistan']

np.float64(31.8)

In [11]:
df.at[2020,'Uzbekistan'] - df.at[2015,'Uzbekistan']

np.float64(3.8000000000000007)

In [12]:
df

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgyzstan  Turkey
2020        33.5        18.8         9.5         6.5     6.0
2019        32.9        18.1         9.3         6.4     5.8
2018        32.5        17.8         8.9         6.3     5.7
2017        31.8        17.5         8.6         6.1     5.5
2016        30.5        17.3         8.3         5.9     5.3
2015        29.7        17.1         7.4         5.5     5.0

In [13]:
df.iat[1,3]

np.float64(6.4)

In [14]:
nums = list(range(10,20))

In [15]:
nums

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [16]:
nums[0]

10

In [17]:
nums[-1]

19

In [18]:
obj = pd.Series(np.arange(10.))

In [19]:
obj

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [20]:
obj[0]

np.float64(0.0)

In [21]:
obj[-1]

KeyError: -1

In [22]:
ser = pd.Series(np.arange(5.0), index = ['a', 'b', 'c', 'd', 'e'])

In [23]:
ser

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [24]:
ser[-1]

/tmp/ipykernel_9073/3387420178.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser[-1]

np.float64(4.0)

In [26]:
obj.iloc[-1]

np.float64(9.0)

In [27]:
obj.iat[-1]

np.float64(9.0)

In [28]:
ser.iloc[-1]

np.float64(4.0)