In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("https://raw.github.com/anvarnarz/praktikum_datasets/main/merc.csv")
df.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
1,S Class,2017,34948,Automatic,27000,Hybrid,20,61.4,2.1
2,SL CLASS,2016,49948,Automatic,6200,Petrol,555,28.0,5.5
3,G Class,2016,61948,Automatic,16000,Petrol,325,30.4,4.0
4,G Class,2016,73948,Automatic,4000,Petrol,325,30.1,4.0

In [3]:
df['model'].unique()

array([' SLK', ' S Class', ' SL CLASS', ' G Class', ' GLE Class',
       ' GLA Class', ' A Class', ' B Class', ' GLC Class', ' C Class',
       ' E Class', ' GL Class', ' CLS Class', ' CLC Class', ' CLA Class',
       ' V Class', ' M Class', ' CL Class', ' GLS Class', ' GLB Class',
       ' X-CLASS', '180', ' CLK', ' R Class', '230', '220', '200'],
      dtype=object)

In [5]:
models = df['model'].unique()
models.sort()
models

array([' A Class', ' B Class', ' C Class', ' CL Class', ' CLA Class',
       ' CLC Class', ' CLK', ' CLS Class', ' E Class', ' G Class',
       ' GL Class', ' GLA Class', ' GLB Class', ' GLC Class',
       ' GLE Class', ' GLS Class', ' M Class', ' R Class', ' S Class',
       ' SL CLASS', ' SLK', ' V Class', ' X-CLASS', '180', '200', '220',
       '230'], dtype=object)

In [10]:
df['year'].unique()

array([2005, 2017, 2016, 2011, 2018, 2012, 2019, 2020, 2014, 2015, 2006,
       2010, 2004, 2008, 2013, 2007, 2009, 2003, 2001, 2002, 1998, 2000,
       1997, 1999, 1970])

In [11]:
df['year'].value_counts()

year
2019    4553
2017    2381
2016    1971
2018    1467
2015     991
2020     719
2014     491
2013     292
2012      57
2010      38
2011      38
2007      22
2009      17
2008      16
2004      13
2001      10
2005       9
2002       9
2006       8
2003       7
1998       4
2000       3
1997       1
1999       1
1970       1
Name: count, dtype: int64

In [12]:
models = [' SLK', ' B Class']
filtr = df['model'].isin(models)
df[filtr]

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
12,B Class,2019,23750,Automatic,278,Diesel,145,55.4,2.0
15,B Class,2017,15890,Automatic,24841,Diesel,150,68.9,1.5
18,B Class,2017,17513,Automatic,14128,Diesel,150,68.9,2.1
40,SLK,2014,15990,Automatic,43955,Petrol,205,43.5,1.8
...,...,...,...,...,...,...,...,...,...
13033,B Class,2016,14599,Automatic,28156,Diesel,20,68.9,2.1
13073,B Class,2019,19350,Automatic,13674,Petrol,145,45.6,1.3
13108,SLK,2016,17499,Automatic,30128,Diesel,30,70.6,2.1
13111,B Class,2019,19344,Automatic,15257,Petrol,145,45.6,1.3
13115,B Class,2020,24699,Automatic,2500,Diesel,145,55.4,2.0

In [13]:
df[df.year<=2018]

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
1,S Class,2017,34948,Automatic,27000,Hybrid,20,61.4,2.1
2,SL CLASS,2016,49948,Automatic,6200,Petrol,555,28.0,5.5
3,G Class,2016,61948,Automatic,16000,Petrol,325,30.4,4.0
4,G Class,2016,73948,Automatic,4000,Petrol,325,30.1,4.0
...,...,...,...,...,...,...,...,...,...
13096,GLE Class,2016,27999,Automatic,27804,Diesel,260,42.8,3.0
13101,GLC Class,2016,23999,Automatic,14000,Diesel,125,56.5,2.1
13102,GLC Class,2017,35999,Automatic,18507,Petrol,150,34.0,3.0
13108,SLK,2016,17499,Automatic,30128,Diesel,30,70.6,2.1
13109,A Class,2017,16499,Automatic,20477,Diesel,145,68.9,2.1

In [14]:
df[(df.year<2018) & (df.mileage<20000)]

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
2,SL CLASS,2016,49948,Automatic,6200,Petrol,555,28.0,5.5
3,G Class,2016,61948,Automatic,16000,Petrol,325,30.4,4.0
4,G Class,2016,73948,Automatic,4000,Petrol,325,30.1,4.0
5,SL CLASS,2011,149948,Automatic,3000,Petrol,570,21.4,6.2
9,GLA Class,2017,19750,Automatic,15258,Diesel,30,64.2,2.1
...,...,...,...,...,...,...,...,...,...
13092,GLE Class,2016,30045,Automatic,18524,Diesel,240,42.8,3.0
13094,GLC Class,2017,30999,Automatic,12376,Diesel,145,56.5,2.1
13095,CLS Class,2016,20399,Automatic,16107,Diesel,160,51.4,3.0
13101,GLC Class,2016,23999,Automatic,14000,Diesel,125,56.5,2.1
13102,GLC Class,2017,35999,Automatic,18507,Petrol,150,34.0,3.0

In [15]:
df[(df.year<2018) & (df.mileage<20000) & (df.price<20000)]

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
9,GLA Class,2017,19750,Automatic,15258,Diesel,30,64.2,2.1
18,B Class,2017,17513,Automatic,14128,Diesel,150,68.9,2.1
43,C Class,2017,19743,Automatic,16509,Diesel,145,61.4,2.1
53,SL CLASS,2010,16990,Automatic,18000,Petrol,555,29.1,3.5
84,CL Class,2015,17863,Semi-Auto,14360,Diesel,20,62.8,2.1
...,...,...,...,...,...,...,...,...,...
13046,SL CLASS,2016,19250,Automatic,19525,Diesel,30,70.6,2.1
13068,SL CLASS,2016,19995,Automatic,13626,Diesel,30,70.6,2.1
13070,SL CLASS,2017,19995,Automatic,18403,Diesel,30,70.6,2.1
13078,SL CLASS,2017,19889,Automatic,17564,Diesel,30,70.6,2.1
13080,E Class,2015,18135,Automatic,18849,Diesel,150,54.3,3.0

In [17]:
df2 = df[(df.year<2018) & (df.mileage<20000) & (df.price<20000)]
df2.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
9,GLA Class,2017,19750,Automatic,15258,Diesel,30,64.2,2.1
18,B Class,2017,17513,Automatic,14128,Diesel,150,68.9,2.1
43,C Class,2017,19743,Automatic,16509,Diesel,145,61.4,2.1
53,SL CLASS,2010,16990,Automatic,18000,Petrol,555,29.1,3.5
84,CL Class,2015,17863,Semi-Auto,14360,Diesel,20,62.8,2.1

In [18]:
df[df.fuelType=='Petrol']

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
2,SL CLASS,2016,49948,Automatic,6200,Petrol,555,28.0,5.5
3,G Class,2016,61948,Automatic,16000,Petrol,325,30.4,4.0
4,G Class,2016,73948,Automatic,4000,Petrol,325,30.1,4.0
5,SL CLASS,2011,149948,Automatic,3000,Petrol,570,21.4,6.2
...,...,...,...,...,...,...,...,...,...
13098,C Class,2019,24499,Automatic,10635,Petrol,145,44.1,1.5
13099,C Class,2019,23994,Automatic,12794,Petrol,145,46.3,1.5
13102,GLC Class,2017,35999,Automatic,18507,Petrol,150,34.0,3.0
13106,C Class,2019,27999,Automatic,6537,Petrol,145,44.1,2.0
13111,B Class,2019,19344,Automatic,15257,Petrol,145,45.6,1.3