In [1]:
import pandas as pd
import numpy as np

In [3]:
from pandas  import Series, DataFrame as df

In [4]:
cars_dict = {"Nexia 2" : 5000, "Gentra" : 15500, "Cobalt" : 14000, "Damas" : 8000, "Nexia 3" : 9000}

In [5]:
cars1 = pd.Series(cars_dict)

In [6]:
cars1

Nexia 2     5000
Gentra     15500
Cobalt     14000
Damas       8000
Nexia 3     9000
dtype: int64

In [8]:
cars1.name = "moshinalar"

In [12]:
cars1.index.name = "Nomlari"

In [13]:
cars1

Nomlari
Nexia 2     5000
Gentra     15500
Cobalt     14000
Damas       8000
Nexia 3     9000
Name: moshinalar, dtype: int64

In [17]:
new_price = Series({"Nexia 2" : 1000, "Lacetti" : 4500, "Malibu" : 20000, "Damas" : 1000, "Nexia 3" : 500, "Cobalt" : 400})

In [18]:
new_price

Nexia 2     1000
Lacetti     4500
Malibu     20000
Damas       1000
Nexia 3      500
Cobalt       400
dtype: int64

In [19]:
cars1+new_price

Cobalt     14400.0
Damas       9000.0
Gentra         NaN
Lacetti        NaN
Malibu         NaN
Nexia 2     6000.0
Nexia 3     9500.0
dtype: float64

In [20]:
cars2 = cars1 + new_price

In [21]:
cars2

Cobalt     14400.0
Damas       9000.0
Gentra         NaN
Lacetti        NaN
Malibu         NaN
Nexia 2     6000.0
Nexia 3     9500.0
dtype: float64

In [23]:
cars2.isnull()

Cobalt     False
Damas      False
Gentra      True
Lacetti     True
Malibu      True
Nexia 2    False
Nexia 3    False
dtype: bool

In [24]:
cars2.notnull()

Cobalt      True
Damas       True
Gentra     False
Lacetti    False
Malibu     False
Nexia 2     True
Nexia 3     True
dtype: bool

In [25]:
cars2.hasnans # NaN qiymatlar bor (True) yo'qligi (False)

True

In [26]:
cars2.is_unique # qiymatlar takrorlanmas ekanini tekshirish

False

In [27]:
cars2.shape # Series hajmi

(7,)

In [28]:
cars2.size # Series hajmi

7

In [30]:
cars2.iloc[6] # ma'lumotlarga indeks tartib raqami bo'yicha murojaat qilish

np.float64(9500.0)

In [31]:
cars2['Nexia 2'] # ma'lumotlarga indeks bo'yicha murojaat qilish

np.float64(6000.0)

In [32]:
cars2.loc['Nexia 2'] # ma'lumotlarga indeks bo'yicha murojaat qilish

np.float64(6000.0)

In [33]:
cars2.max() # max qiymat

14400.0

In [34]:
cars2.min() # min qiymat

6000.0

In [35]:
cars2.mean() # o'rtacha qiymat

np.float64(9725.0)

In [37]:
cars_3 = Series({"BMW" : 50000, "Mers" : "oltmishming, "Tico" : "beshuz"})

SyntaxError: unterminated string literal (detected at line 1) (2992345888.py, line 1)