In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population.csv", index_col=0)
df.head()

        country     density   densityMi   pop2021  area
rank
1         Macau  21946.4667  56841.3487   658.394    30
2        Monaco  19755.5000  51166.7450    39.511     2
3     Singapore   8305.1915  21510.4461  5896.686   710
4     Hong Kong   6841.3134  17719.0017  7552.810  1104
5     Gibraltar   5616.3333  14546.3033    33.698     6

In [3]:
columns = ['davlat','zichlik_km','zichlik_mi','aholi','maydoni']
df.columns = columns
df.head(3)

         davlat  zichlik_km  zichlik_mi     aholi  maydoni
rank
1         Macau  21946.4667  56841.3487   658.394       30
2        Monaco  19755.5000  51166.7450    39.511        2
3     Singapore   8305.1915  21510.4461  5896.686      710

In [4]:
df.tail(10)

                davlat  zichlik_km  zichlik_mi      aholi  maydoni
rank
223             Guyana      3.6765      9.5220    790.326   214969
224      French Guiana      3.6685      9.5015    306.448    83534
225           Suriname      3.6125      9.3564    591.800   163820
226          Australia      3.3526      8.6832  25788.215  7692024
227            Iceland      3.3335      8.6338    343.353   103000
228            Namibia      3.1338      8.1166   2587.344   825615
229     Western Sahara      2.3003      5.9577    611.875   266000
230           Mongolia      2.1286      5.5129   3329.289  1564110
231   Falkland Islands      0.2902      0.7517      3.533    12173
232          Greenland      0.0263      0.0680     56.877  2166086

In [6]:
df1 = df[(df.index==10) | (df.index==20) | (df.index==100) | (df.index==200)]
df1

           davlat  zichlik_km  zichlik_mi     aholi  maydoni
rank
10        Bermuda   1149.8148   2978.0204    62.090       54
20          Aruba    595.5778   1542.5464   107.204      180
100      Slovakia    111.3592    288.4203  5460.721    49037
200   New Zealand     17.9713     46.5457  4860.643   270467

In [7]:
df.head()

         davlat  zichlik_km  zichlik_mi     aholi  maydoni
rank
1         Macau  21946.4667  56841.3487   658.394       30
2        Monaco  19755.5000  51166.7450    39.511        2
3     Singapore   8305.1915  21510.4461  5896.686      710
4     Hong Kong   6841.3134  17719.0017  7552.810     1104
5     Gibraltar   5616.3333  14546.3033    33.698        6

In [8]:
df_uz = df[df.davlat=='Uzbekistan']
df_uz

          davlat  zichlik_km  zichlik_mi      aholi  maydoni
rank
133   Uzbekistan     75.8511    196.4542  33935.763   447400

In [11]:
dav = ['Uzbekistan', 'Hong-Kong', 'Antartica']
df.davlat.isin(dav).value_counts()

davlat
False    231
True       1
Name: count, dtype: int64

In [18]:
df.head(10)

            davlat  zichlik_km  zichlik_mi     aholi  maydoni
rank
1            Macau  21946.4667  56841.3487   658.394       30
2           Monaco  19755.5000  51166.7450    39.511        2
3        Singapore   8305.1915  21510.4461  5896.686      710
4        Hong Kong   6841.3134  17719.0017  7552.810     1104
5        Gibraltar   5616.3333  14546.3033    33.698        6
6          Bahrain   2285.3542   5919.0675  1748.296      765
7         Maldives   1812.0567   4693.2268   543.617      300
8            Malta   1401.2152   3629.1473   442.784      316
9     Sint Maarten   1276.8235   3306.9729    43.412       34
10         Bermuda   1149.8148   2978.0204    62.090       54

In [20]:
df.index = df.davlat
df.head(10)

                    davlat  zichlik_km  zichlik_mi     aholi  maydoni
davlat
Macau                Macau  21946.4667  56841.3487   658.394       30
Monaco              Monaco  19755.5000  51166.7450    39.511        2
Singapore        Singapore   8305.1915  21510.4461  5896.686      710
Hong Kong        Hong Kong   6841.3134  17719.0017  7552.810     1104
Gibraltar        Gibraltar   5616.3333  14546.3033    33.698        6
Bahrain            Bahrain   2285.3542   5919.0675  1748.296      765
Maldives          Maldives   1812.0567   4693.2268   543.617      300
Malta                Malta   1401.2152   3629.1473   442.784      316
Sint Maarten  Sint Maarten   1276.8235   3306.9729    43.412       34
Bermuda            Bermuda   1149.8148   2978.0204    62.090       54

In [27]:
df.drop('davlat', axis=1)

                  zichlik_km  zichlik_mi     aholi  maydoni
davlat
Macau             21946.4667  56841.3487   658.394       30
Monaco            19755.5000  51166.7450    39.511        2
Singapore          8305.1915  21510.4461  5896.686      710
Hong Kong          6841.3134  17719.0017  7552.810     1104
Gibraltar          5616.3333  14546.3033    33.698        6
...                      ...         ...       ...      ...
Namibia               3.1338      8.1166  2587.344   825615
Western Sahara        2.3003      5.9577   611.875   266000
Mongolia              2.1286      5.5129  3329.289  1564110
Falkland Islands      0.2902      0.7517     3.533    12173
Greenland             0.0263      0.0680    56.877  2166086

[232 rows x 4 columns]

In [28]:
df.head(10)

                    davlat  zichlik_km  zichlik_mi     aholi  maydoni
davlat
Macau                Macau  21946.4667  56841.3487   658.394       30
Monaco              Monaco  19755.5000  51166.7450    39.511        2
Singapore        Singapore   8305.1915  21510.4461  5896.686      710
Hong Kong        Hong Kong   6841.3134  17719.0017  7552.810     1104
Gibraltar        Gibraltar   5616.3333  14546.3033    33.698        6
Bahrain            Bahrain   2285.3542   5919.0675  1748.296      765
Maldives          Maldives   1812.0567   4693.2268   543.617      300
Malta                Malta   1401.2152   3629.1473   442.784      316
Sint Maarten  Sint Maarten   1276.8235   3306.9729    43.412       34
Bermuda            Bermuda   1149.8148   2978.0204    62.090       54

In [38]:
df.sort_index()

,davlat,zichlik_km,zichlik_mi,aholi,maydoni
davlat,,,,,
Afghanistan,Afghanistan,61.0757,158.1862,39835.428,652230
Albania,Albania,99.9351,258.8318,2872.933,28748
Algeria,Algeria,18.7328,48.5179,44616.624,2381741
American Samoa,American Samoa,276.8844,717.1307,55.100,199
Andorra,Andorra,165.2885,428.0971,77.355,468
...,...,...,...,...,...
Wallis and Futuna,Wallis and Futuna,78.1268,202.3483,11.094,142
Western Sahara,Western Sahara,2.3003,5.9577,611.875,266000
Yemen,Yemen,57.7509,149.5749,30490.640,527968
Zambia,Zambia,25.1400,65.1125,18920.651,752612
Zimbabwe,Zimbabwe,38.6229,100.0333,15092.171,390757

In [40]:
davlatlar = ['Uzbekistan', 'Malaysia', 'South Korea', 'France']
ustuns = ['aholi', 'maydoni']

davlats = df.loc[df.index.isin(davlatlar), ustuns]
davlats

                 aholi  maydoni
davlat
South Korea  51305.186   100210
France       65426.179   551695
Malaysia     32776.194   330803
Uzbekistan   33935.763   447400

In [41]:
df.head()

              davlat  zichlik_km  zichlik_mi     aholi  maydoni
davlat
Macau          Macau  21946.4667  56841.3487   658.394       30
Monaco        Monaco  19755.5000  51166.7450    39.511        2
Singapore  Singapore   8305.1915  21510.4461  5896.686      710
Hong Kong  Hong Kong   6841.3134  17719.0017  7552.810     1104
Gibraltar  Gibraltar   5616.3333  14546.3033    33.698        6

In [42]:
df.aholi = df.aholi*1000

In [43]:
df

                            davlat  zichlik_km  zichlik_mi      aholi  maydoni
davlat
Macau                        Macau  21946.4667  56841.3487   658394.0       30
Monaco                      Monaco  19755.5000  51166.7450    39511.0        2
Singapore                Singapore   8305.1915  21510.4461  5896686.0      710
Hong Kong                Hong Kong   6841.3134  17719.0017  7552810.0     1104
Gibraltar                Gibraltar   5616.3333  14546.3033    33698.0        6
...                            ...         ...         ...        ...      ...
Namibia                    Namibia      3.1338      8.1166  2587344.0   825615
Western Sahara      Western Sahara      2.3003      5.9577   611875.0   266000
Mongolia                  Mongolia      2.1286      5.5129  3329289.0  1564110
Falkland Islands  Falkland Islands      0.2902      0.7517     3533.0    12173
Greenland                Greenland      0.0263      0.0680    56877.0  2166086

[232 rows x 5 columns]

In [44]:
df.sort_values(by='aholi', ascending=False).head(10)

                      davlat  zichlik_km  zichlik_mi         aholi   maydoni
davlat
China                  China    148.7815    385.3441  1.444216e+09   9706961
India                  India    423.8391   1097.7432  1.393409e+09   3287590
United States  United States     35.5200     91.9968  3.329151e+08   9372610
Indonesia          Indonesia    145.1046    375.8210  2.763618e+08   1904569
Pakistan            Pakistan    255.3542    661.3674  2.251999e+08    881912
Brazil                Brazil     25.1291     65.0843  2.139934e+08   8515767
Nigeria              Nigeria    228.8461    592.7114  2.114007e+08    923768
Bangladesh        Bangladesh   1126.9465   2918.7915  1.663035e+08    147570
Russia                Russia      8.5337     22.1024  1.459120e+08  17098242
Mexico                Mexico     66.3123    171.7488  1.302622e+08   1964375

In [46]:
df['rank'] = df['maydoni'].rank()
df.head()

              davlat  zichlik_km  zichlik_mi      aholi  maydoni  rank
davlat
Macau          Macau  21946.4667  56841.3487   658394.0       30   8.0
Monaco        Monaco  19755.5000  51166.7450    39511.0        2   2.0
Singapore  Singapore   8305.1915  21510.4461  5896686.0      710  43.0
Hong Kong  Hong Kong   6841.3134  17719.0017  7552810.0     1104  50.0
Gibraltar  Gibraltar   5616.3333  14546.3033    33698.0        6   3.0

In [49]:
dav= ['Uzbekistan', 'United Kingdom', 'Indonesia']

newdf = df.loc[df.index.isin(dav)]
newdf

,davlat,zichlik_km,zichlik_mi,aholi,maydoni,rank
davlat,,,,,,
United Kingdom,United Kingdom,280.8033,727.2805,68207116.0,242900,153.0
Indonesia,Indonesia,145.1046,375.8210,276361783.0,1904569,218.0
Uzbekistan,Uzbekistan,75.8511,196.4542,33935763.0,447400,176.0

In [50]:
df.sort_index()

,davlat,zichlik_km,zichlik_mi,aholi,maydoni,rank
davlat,,,,,,
Afghanistan,Afghanistan,61.0757,158.1862,39835428.0,652230,192.0
Albania,Albania,99.9351,258.8318,2872933.0,28748,89.0
Algeria,Algeria,18.7328,48.5179,44616624.0,2381741,223.0
American Samoa,American Samoa,276.8844,717.1307,55100.0,199,20.0
Andorra,Andorra,165.2885,428.0971,77355.0,468,38.0
...,...,...,...,...,...,...
Wallis and Futuna,Wallis and Futuna,78.1268,202.3483,11094.0,142,15.0
Western Sahara,Western Sahara,2.3003,5.9577,611875.0,266000,155.0
Yemen,Yemen,57.7509,149.5749,30490640.0,527968,183.0
Zambia,Zambia,25.1400,65.1125,18920651.0,752612,194.0
Zimbabwe,Zimbabwe,38.6229,100.0333,15092171.0,390757,172.0