In [40]:
import numpy as np
import pandas as pd

In [41]:
data = {
    'Yil' : [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
    'Aholi soni' : [33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
    'Temp' : [1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53],
    'Zichlik' : [79.77, 78.68, 77.53, 76.34, 75.13, 73.91, 72.71, 67.03]
}
df = pd.DataFrame(data)
df

    Yil  Aholi soni  Temp  Zichlik
0  2021        33.9  1.54    79.77
1  2020        33.5  1.48    78.68
2  2019        32.9  1.56    77.53
3  2018        32.5  1.62    76.34
4  2017        31.9  1.65    75.13
5  2016        31.4  1.66    73.91
6  2015        30.9  1.64    72.71
7  2010        28.5  1.53    67.03

In [42]:
ind = [10, 15, 17, 16, 18, 19, 20, 21]
ind

[10, 15, 17, 16, 18, 19, 20, 21]

In [43]:
ind.sort()
ind

[10, 15, 16, 17, 18, 19, 20, 21]

In [44]:
df.index = [21, 20, 19, 18, 17, 16, 15, 10]

In [45]:
df.sample()

     Yil  Aholi soni  Temp  Zichlik
17  2017        31.9  1.65    75.13

In [18]:
df

     Yil  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
20  2020        33.5  1.48    78.68
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13
16  2016        31.4  1.66    73.91
15  2015        30.9  1.64    72.71
10  2010        28.5  1.53    67.03

In [49]:
df = df.reindex(ind)

In [50]:
df

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [51]:
df2 = df.drop(15)
df2

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [52]:
df.drop([18, 17])

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [53]:
df.drop('Yil', axis=1)

    Aholi soni  Temp  Zichlik
10        28.5  1.53    67.03
15        30.9  1.64    72.71
16        31.4  1.66    73.91
17        31.9  1.65    75.13
18        32.5  1.62    76.34
19        32.9  1.56    77.53
20        33.5  1.48    78.68
21        33.9  1.54    79.77

In [54]:
df

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [55]:
df_inplace1 = df

In [56]:
df_inplace1

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [57]:
df

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [58]:
#inplace_True_Joyida_saqlab_ketadi
df_inplace1.drop('Yil', axis=1, inplace=True)

In [59]:
df_inplace1

    Aholi soni  Temp  Zichlik
10        28.5  1.53    67.03
15        30.9  1.64    72.71
16        31.4  1.66    73.91
17        31.9  1.65    75.13
18        32.5  1.62    76.34
19        32.9  1.56    77.53
20        33.5  1.48    78.68
21        33.9  1.54    79.77