In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Yil' : [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
    'Aholi soni' : [33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
    'Temp' : [1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53],
    'Zichlik' : [79.77, 78.68, 77.53, 76.34, 75.13, 73.91, 72.71, 67.03]
}
df = pd.DataFrame(data)
df

    Yil  Aholi soni  Temp  Zichlik
0  2021        33.9  1.54    79.77
1  2020        33.5  1.48    78.68
2  2019        32.9  1.56    77.53
3  2018        32.5  1.62    76.34
4  2017        31.9  1.65    75.13
5  2016        31.4  1.66    73.91
6  2015        30.9  1.64    72.71
7  2010        28.5  1.53    67.03

In [4]:
df.index = [21, 20, 19, 18, 17, 16, 15, 10]
df

     Yil  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
20  2020        33.5  1.48    78.68
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13
16  2016        31.4  1.66    73.91
15  2015        30.9  1.64    72.71
10  2010        28.5  1.53    67.03

In [5]:
#Reindex
ind = [21, 20, 19, 18, 17, 16, 15, 10]
ind.sort()
ind

[10, 15, 16, 17, 18, 19, 20, 21]

In [6]:
df.reindex(ind)

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [7]:
df

     Yil  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
20  2020        33.5  1.48    78.68
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13
16  2016        31.4  1.66    73.91
15  2015        30.9  1.64    72.71
10  2010        28.5  1.53    67.03

In [8]:
df.reindex([10, 15, 20])

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
15  2015        30.9  1.64    72.71
20  2020        33.5  1.48    78.68

In [10]:
df.reindex(index=range(10, 22))

       Yil  Aholi soni  Temp  Zichlik
10  2010.0        28.5  1.53    67.03
11     NaN         NaN   NaN      NaN
12     NaN         NaN   NaN      NaN
13     NaN         NaN   NaN      NaN
14     NaN         NaN   NaN      NaN
15  2015.0        30.9  1.64    72.71
16  2016.0        31.4  1.66    73.91
17  2017.0        31.9  1.65    75.13
18  2018.0        32.5  1.62    76.34
19  2019.0        32.9  1.56    77.53
20  2020.0        33.5  1.48    78.68
21  2021.0        33.9  1.54    79.77

In [11]:
df.reindex(index=range(10, 22), method='nearest')

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
11  2010        28.5  1.53    67.03
12  2010        28.5  1.53    67.03
13  2015        30.9  1.64    72.71
14  2015        30.9  1.64    72.71
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [12]:
df.reindex(index=range(10, 22), method='ffill')

     Yil  Aholi soni  Temp  Zichlik
10  2010        28.5  1.53    67.03
11  2015        30.9  1.64    72.71
12  2015        30.9  1.64    72.71
13  2015        30.9  1.64    72.71
14  2015        30.9  1.64    72.71
15  2015        30.9  1.64    72.71
16  2016        31.4  1.66    73.91
17  2017        31.9  1.65    75.13
18  2018        32.5  1.62    76.34
19  2019        32.9  1.56    77.53
20  2020        33.5  1.48    78.68
21  2021        33.9  1.54    79.77

In [13]:
df.reindex(columns=['Aholi soni', 'Temp', 'Zichlik'])

    Aholi soni  Temp  Zichlik
21        33.9  1.54    79.77
20        33.5  1.48    78.68
19        32.9  1.56    77.53
18        32.5  1.62    76.34
17        31.9  1.65    75.13
16        31.4  1.66    73.91
15        30.9  1.64    72.71
10        28.5  1.53    67.03

In [14]:
df.head()

     Yil  Aholi soni  Temp  Zichlik
21  2021        33.9  1.54    79.77
20  2020        33.5  1.48    78.68
19  2019        32.9  1.56    77.53
18  2018        32.5  1.62    76.34
17  2017        31.9  1.65    75.13

In [15]:
df.sample()

     Yil  Aholi soni  Temp  Zichlik
19  2019        32.9  1.56    77.53

In [16]:
df.sample(3)

     Yil  Aholi soni  Temp  Zichlik
16  2016        31.4  1.66    73.91
19  2019        32.9  1.56    77.53
17  2017        31.9  1.65    75.13

In [19]:
df.loc[[10,15,18,20], ['Aholi soni', 'Temp', 'Zichlik']]

    Aholi soni  Temp  Zichlik
10        28.5  1.53    67.03
15        30.9  1.64    72.71
18        32.5  1.62    76.34
20        33.5  1.48    78.68