In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/usa_cars.csv", index_col=0)
df.head()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left

In [3]:
df['rating'] = df['year'].rank()

In [4]:
df

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,rating
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left,70.5
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left,115.0
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left,1362.0
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left,336.5
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left,1362.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2494,7800,nissan,versa,2019,clean vehicle,23609,red,3n1cn7ap9kl880319,167722715,california,usa,1 days left,2005.5
2495,9200,nissan,versa,2018,clean vehicle,34553,silver,3n1cn7ap5jl884088,167762225,florida,usa,21 hours left,1362.0
2496,9200,nissan,versa,2018,clean vehicle,31594,silver,3n1cn7ap9jl884191,167762226,florida,usa,21 hours left,1362.0
2497,9200,nissan,versa,2018,clean vehicle,32557,black,3n1cn7ap3jl883263,167762227,florida,usa,2 days left,1362.0
2498,9200,nissan,versa,2018,clean vehicle,31371,silver,3n1cn7ap4jl884311,167762228,florida,usa,21 hours left,1362.0

In [6]:
df['rating'] = df['mileage'].rank()
df.sort_values(by='rating')

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,rating
545,0,gmc,door,1993,salvage insurance,0,light blue,1gkfk16k5pj701631,167358601,colorado,usa,18 hours left,3.5
1236,4200,ford,door,2013,clean vehicle,0,no_color,1fadp3j23dl155179,167773673,pennsylvania,usa,2 days left,3.5
309,0,chevrolet,door,2004,salvage insurance,0,maroon,3gnek12t74g240524,167418651,wyoming,usa,18 hours left,3.5
322,0,ford,chassis,1994,salvage insurance,0,green,1fdee14n7rha47894,167359174,california,usa,19 hours left,3.5
504,100,peterbilt,truck,2012,salvage insurance,0,blue,1xp4d49x1cd144875,167529787,florida,usa,17 hours left,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
531,2000,chevrolet,pickup,2003,clean vehicle,507985,red,1gcgc24u53z128586,167781223,wisconsin,usa,21 hours left,2495.0
490,475,peterbilt,truck,2012,salvage insurance,902041,gold,1xp4d49x9cd123630,167529786,florida,usa,17 hours left,2496.0
516,0,peterbilt,truck,2009,salvage insurance,982486,blue,1xp7d49x09d784257,167529788,florida,usa,17 hours left,2497.0
1827,3200,ford,door,2013,clean vehicle,999999,silver,1fadp3k21dl266148,167727773,south carolina,usa,21 hours left,2498.0
528,1025,peterbilt,truck,2010,salvage insurance,1017936,color:,1xp7d49x0ad793710,167529842,georgia,usa,17 hours left,2499.0

In [7]:
df['rating'] = df['price'].rank(method='min')
df.sort_values(by='rating')

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,rating
455,0,chevrolet,door,2006,salvage insurance,268040,silver,1g1zt53f46f254868,167650486,texas,usa,17 hours left,1.0
421,0,bmw,door,2000,salvage insurance,216657,gray,wbaam3346yfp77118,167425906,utah,usa,2 days left,1.0
420,0,audi,door,2005,salvage insurance,181896,black,waudg74f05n113751,167419563,california,usa,19 hours left,1.0
419,0,kia,wagon,2008,salvage insurance,148463,silver,knafg525787197602,167247592,indiana,usa,16 hours left,1.0
293,0,chevrolet,pickup,1998,salvage insurance,258631,gray,1gccs1445wk226994,167417659,texas,usa,17 hours left,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215,65500,ford,srw,2019,clean vehicle,6500,black,1ft7w2bt0kec44818,167718954,indiana,usa,21 hours left,2495.0
277,67000,dodge,challenger,2019,clean vehicle,10944,blue,2c3cdzl97kh518237,167759490,ohio,usa,21 hours left,2496.0
1336,70000,ford,drw,2019,clean vehicle,9643,no_color,1ft8w3dt3kee48276,167780680,illinois,usa,2 days left,2497.0
1340,74000,ford,drw,2019,clean vehicle,10536,no_color,1ft8w4dt6ked32656,167780682,illinois,usa,2 days left,2498.0
502,84900,mercedes-benz,sl-class,2017,clean vehicle,25302,silver,wddjk7ea3hf044968,167607883,florida,usa,2 days left,2499.0

In [10]:
df['rating'] = df['mileage'].rank(method='average')  #average o'rtachasi
df.sort_values(by='rating')

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,rating
545,0,gmc,door,1993,salvage insurance,0,light blue,1gkfk16k5pj701631,167358601,colorado,usa,18 hours left,3.5
1236,4200,ford,door,2013,clean vehicle,0,no_color,1fadp3j23dl155179,167773673,pennsylvania,usa,2 days left,3.5
309,0,chevrolet,door,2004,salvage insurance,0,maroon,3gnek12t74g240524,167418651,wyoming,usa,18 hours left,3.5
322,0,ford,chassis,1994,salvage insurance,0,green,1fdee14n7rha47894,167359174,california,usa,19 hours left,3.5
504,100,peterbilt,truck,2012,salvage insurance,0,blue,1xp4d49x1cd144875,167529787,florida,usa,17 hours left,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
531,2000,chevrolet,pickup,2003,clean vehicle,507985,red,1gcgc24u53z128586,167781223,wisconsin,usa,21 hours left,2495.0
490,475,peterbilt,truck,2012,salvage insurance,902041,gold,1xp4d49x9cd123630,167529786,florida,usa,17 hours left,2496.0
516,0,peterbilt,truck,2009,salvage insurance,982486,blue,1xp7d49x09d784257,167529788,florida,usa,17 hours left,2497.0
1827,3200,ford,door,2013,clean vehicle,999999,silver,1fadp3k21dl266148,167727773,south carolina,usa,21 hours left,2498.0
528,1025,peterbilt,truck,2010,salvage insurance,1017936,color:,1xp7d49x0ad793710,167529842,georgia,usa,17 hours left,2499.0