In [1]:
import pandas as pd
import numpy as np

In [3]:
obj = pd.Series(range(4), index=['d', 'c', 'a', 'b'])
obj

d    0
c    1
a    2
b    3
dtype: int64

In [4]:
obj.sort_index()

a    2
b    3
c    1
d    0
dtype: int64

In [5]:
obj.sort_values()
#

d    0
c    1
a    2
b    3
dtype: int64

In [6]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/usa_cars.csv", index_col=0)
df.head()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left

In [7]:
df.shape

(2499, 12)

In [8]:
df.sort_index

<bound method DataFrame.sort_index of       price      brand    model  year   title_status  mileage   color  \
0      6300     toyota  cruiser  2008  clean vehicle   274117   black
1      2899       ford       se  2011  clean vehicle   190552  silver
2      5350      dodge      mpv  2018  clean vehicle    39590  silver
3     25000       ford     door  2014  clean vehicle    64146    blue
4     27700  chevrolet     1500  2018  clean vehicle     6654     red
...     ...        ...      ...   ...            ...      ...     ...
2494   7800     nissan    versa  2019  clean vehicle    23609     red
2495   9200     nissan    versa  2018  clean vehicle    34553  silver
2496   9200     nissan    versa  2018  clean vehicle    31594  silver
2497   9200     nissan    versa  2018  clean vehicle    32557   black
2498   9200     nissan    versa  2018  clean vehicle    31371  silver

                      vin        lot       state country      condition
0       jtezu11f88k007763  159348797  new jersey     usa   10 days left
1       2fmdk3gc4bbb02217  166951262   tennessee     usa    6 days left
2       3c4pdcgg5jt346413  167655728     georgia     usa    2 days left
3       1ftfw1et4efc23745  167753855    virginia     usa  22 hours left
4       3gcpcrec2jg473991  167763266     florida     usa  22 hours left
...                   ...        ...         ...     ...            ...
2494    3n1cn7ap9kl880319  167722715  california     usa    1 days left
2495    3n1cn7ap5jl884088  167762225     florida     usa  21 hours left
2496    3n1cn7ap9jl884191  167762226     florida     usa  21 hours left
2497    3n1cn7ap3jl883263  167762227     florida     usa    2 days left
2498    3n1cn7ap4jl884311  167762228     florida     usa  21 hours left

[2499 rows x 12 columns]>

In [9]:
df.sort_index(axis=1)

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,nissan,red,1 days left,usa,167722715,23609,versa,7800,california,clean vehicle,3n1cn7ap9kl880319,2019
2495,nissan,silver,21 hours left,usa,167762225,34553,versa,9200,florida,clean vehicle,3n1cn7ap5jl884088,2018
2496,nissan,silver,21 hours left,usa,167762226,31594,versa,9200,florida,clean vehicle,3n1cn7ap9jl884191,2018
2497,nissan,black,2 days left,usa,167762227,32557,versa,9200,florida,clean vehicle,3n1cn7ap3jl883263,2018
2498,nissan,silver,21 hours left,usa,167762228,31371,versa,9200,florida,clean vehicle,3n1cn7ap4jl884311,2018

In [10]:
df.sort_index(ascending=False)

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
2498,9200,nissan,versa,2018,clean vehicle,31371,silver,3n1cn7ap4jl884311,167762228,florida,usa,21 hours left
2497,9200,nissan,versa,2018,clean vehicle,32557,black,3n1cn7ap3jl883263,167762227,florida,usa,2 days left
2496,9200,nissan,versa,2018,clean vehicle,31594,silver,3n1cn7ap9jl884191,167762226,florida,usa,21 hours left
2495,9200,nissan,versa,2018,clean vehicle,34553,silver,3n1cn7ap5jl884088,167762225,florida,usa,21 hours left
2494,7800,nissan,versa,2019,clean vehicle,23609,red,3n1cn7ap9kl880319,167722715,california,usa,1 days left
...,...,...,...,...,...,...,...,...,...,...,...,...
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left

In [11]:
df

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,7800,nissan,versa,2019,clean vehicle,23609,red,3n1cn7ap9kl880319,167722715,california,usa,1 days left
2495,9200,nissan,versa,2018,clean vehicle,34553,silver,3n1cn7ap5jl884088,167762225,florida,usa,21 hours left
2496,9200,nissan,versa,2018,clean vehicle,31594,silver,3n1cn7ap9jl884191,167762226,florida,usa,21 hours left
2497,9200,nissan,versa,2018,clean vehicle,32557,black,3n1cn7ap3jl883263,167762227,florida,usa,2 days left
2498,9200,nissan,versa,2018,clean vehicle,31371,silver,3n1cn7ap4jl884311,167762228,florida,usa,21 hours left

In [12]:
df.sort_index(axis=1, ascending=False)

,year,vin,title_status,state,price,model,mileage,lot,country,condition,color,brand
0,2008,jtezu11f88k007763,clean vehicle,new jersey,6300,cruiser,274117,159348797,usa,10 days left,black,toyota
1,2011,2fmdk3gc4bbb02217,clean vehicle,tennessee,2899,se,190552,166951262,usa,6 days left,silver,ford
2,2018,3c4pdcgg5jt346413,clean vehicle,georgia,5350,mpv,39590,167655728,usa,2 days left,silver,dodge
3,2014,1ftfw1et4efc23745,clean vehicle,virginia,25000,door,64146,167753855,usa,22 hours left,blue,ford
4,2018,3gcpcrec2jg473991,clean vehicle,florida,27700,1500,6654,167763266,usa,22 hours left,red,chevrolet
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,2019,3n1cn7ap9kl880319,clean vehicle,california,7800,versa,23609,167722715,usa,1 days left,red,nissan
2495,2018,3n1cn7ap5jl884088,clean vehicle,florida,9200,versa,34553,167762225,usa,21 hours left,silver,nissan
2496,2018,3n1cn7ap9jl884191,clean vehicle,florida,9200,versa,31594,167762226,usa,21 hours left,silver,nissan
2497,2018,3n1cn7ap3jl883263,clean vehicle,florida,9200,versa,32557,167762227,usa,2 days left,black,nissan
2498,2018,3n1cn7ap4jl884311,clean vehicle,florida,9200,versa,31371,167762228,usa,21 hours left,silver,nissan

In [13]:
df.sort_values(by='price')

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
455,0,chevrolet,door,2006,salvage insurance,268040,silver,1g1zt53f46f254868,167650486,texas,usa,17 hours left
421,0,bmw,door,2000,salvage insurance,216657,gray,wbaam3346yfp77118,167425906,utah,usa,2 days left
420,0,audi,door,2005,salvage insurance,181896,black,waudg74f05n113751,167419563,california,usa,19 hours left
419,0,kia,wagon,2008,salvage insurance,148463,silver,knafg525787197602,167247592,indiana,usa,16 hours left
293,0,chevrolet,pickup,1998,salvage insurance,258631,gray,1gccs1445wk226994,167417659,texas,usa,17 hours left
...,...,...,...,...,...,...,...,...,...,...,...,...
1215,65500,ford,srw,2019,clean vehicle,6500,black,1ft7w2bt0kec44818,167718954,indiana,usa,21 hours left
277,67000,dodge,challenger,2019,clean vehicle,10944,blue,2c3cdzl97kh518237,167759490,ohio,usa,21 hours left
1336,70000,ford,drw,2019,clean vehicle,9643,no_color,1ft8w3dt3kee48276,167780680,illinois,usa,2 days left
1340,74000,ford,drw,2019,clean vehicle,10536,no_color,1ft8w4dt6ked32656,167780682,illinois,usa,2 days left
502,84900,mercedes-benz,sl-class,2017,clean vehicle,25302,silver,wddjk7ea3hf044968,167607883,florida,usa,2 days left

In [14]:
df.sort_values(by=['price'], ascending=False)

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
502,84900,mercedes-benz,sl-class,2017,clean vehicle,25302,silver,wddjk7ea3hf044968,167607883,florida,usa,2 days left
1340,74000,ford,drw,2019,clean vehicle,10536,no_color,1ft8w4dt6ked32656,167780682,illinois,usa,2 days left
1336,70000,ford,drw,2019,clean vehicle,9643,no_color,1ft8w3dt3kee48276,167780680,illinois,usa,2 days left
277,67000,dodge,challenger,2019,clean vehicle,10944,blue,2c3cdzl97kh518237,167759490,ohio,usa,21 hours left
1215,65500,ford,srw,2019,clean vehicle,6500,black,1ft7w2bt0kec44818,167718954,indiana,usa,21 hours left
...,...,...,...,...,...,...,...,...,...,...,...,...
318,0,chevrolet,door,2009,salvage insurance,117059,black,kl1td66e39b645208,167418694,colorado,usa,18 hours left
305,0,ford,door,2003,salvage insurance,246065,gold,1fafp55u03a242094,167610324,kansas,usa,8 days left
510,0,ford,door,2010,salvage insurance,86841,silver,3fahp0ga3ar366961,167357806,oklahoma,usa,17 hours left
522,0,ford,door,2008,salvage insurance,145483,red,1fmcu03128kc80487,167357813,oklahoma,usa,17 hours left
144,0,dodge,door,2014,salvage insurance,123660,silver,1c3cdzab0en111068,167756167,utah,usa,2 days left

In [15]:
df.sort_values(by=['year', 'price'])

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
32,29800,chevrolet,camaro,1973,clean vehicle,46226,red,1q87t3n166389,167763370,pennsylvania,usa,22 hours left
405,25,ford,door,1984,salvage insurance,41577,white,2ftcf15y9eca14589,167611661,arkansas,usa,17 hours left
545,0,gmc,door,1993,salvage insurance,0,light blue,1gkfk16k5pj701631,167358601,colorado,usa,18 hours left
322,0,ford,chassis,1994,salvage insurance,0,green,1fdee14n7rha47894,167359174,california,usa,19 hours left
362,25,ford,pickup,1994,salvage insurance,206162,white,1ftdf15y2rnb12612,167361489,georgia,usa,2 days left
...,...,...,...,...,...,...,...,...,...,...,...,...
225,45500,chevrolet,tahoe,2020,clean vehicle,13885,white,1gnscbkc6lr159535,167766009,georgia,usa,3 days left
1701,46900,ford,explorer,2020,clean vehicle,740,gray,1fmsk8fh3lga11841,167751303,virginia,usa,21 hours left
426,55600,lexus,gx,2020,clean vehicle,8186,silver,jtjam7bx4l5251250,167605747,florida,usa,2 days left
2088,59900,ford,max,2020,clean vehicle,2162,no_color,1fmjk2at4lea11492,167762991,ohio,usa,21 hours left
399,61200,bmw,series,2020,clean vehicle,7509,black,wba7t2c04lgl17687,167417053,california,usa,7 days left